export const iconSize = 16;
export const iconMargin = 15;
export const photoSize = 40;
export const borderRadius = 50;
export const expandDuration = 0.65;
export const fixedRight = 20 - iconMargin;
export const fixedBottom = 38 - 8;
export const fixedRightTablet = 30 - iconMargin;
export const fixedBottomTablet = 60 - 18;
